### ISSUE TITLE
Questions about translation

### ISSUE THREAD

**Issue by pedroaugustobt** [moo-man/WrathAndGlory-FoundryVTT#246] opened 2024-02-10 21:50 UTC
I'm translating the system into PT-BR and I encountered some difficulties, can anyone who has already translated or understands some of this help me?

The translation of the Traits descriptions does not appear in the en.json file, however this is what appears in the system's base script:
![image](https://github.com/moo-man/WrathAndGlory-FoundryVTT/assets/107325727/e6ac1dd3-0263-4fed-bac7-477f0c36f218)

**Comment by moo-man** [comment] 2024-02-10 21:56
Trait descriptions are text from the book, which is not permissible to include in a freely distributed system. 

Closing this as this is not a bug, if you have questions or want to discuss, the Discord is always available.

**Closed by moo-man** 2024-02-10 21:56 UTC
